### ISSUE TITLE
CustomEventInit is now generic

### ISSUE THREAD

**Issue by bzuu-ic** [thoth-org/Thoth.Elmish.Toast#30]
16 days ago `CustomerEventInit` was made generic in the Fable Browser repo:

https://github.com/fable-compiler/fable-browser/commit/53a4cbd4976bf9b795ed8b281540175b5e1c51c0

As a result when using the latest version together with Thoth.Elmish.Toast you get the following compiler error:

```
The type 'Browser.Types.CustomEventInit<_>' expects 1 type argument(s) but is given 0 (code 33)
```

**Comment by alfonsogarciacaro** [comment]
Sorry for this, I should have avoided the breaking change. I've added back the non-generic `CustomEvent` type (along with the new generic version) in Fable.Browser.Event 1.4.5. Could you please try updating to see if this fixes the issue (without changes to Toth.Elmish.Toast? Thanks a lot for reporting this and sorry again for the trouble!

**Comment by MangelMaxime** [comment]
Fable.Browser.Event 1.4.5 fix the problem

**Comment by bzuu-ic** [comment]
@alfonsogarciacaro and @MangelMaxime I've just updated to the latest versions and everything seems to be working again. Thanks for the quick solution!
